apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc.fullname" . }}-service
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
    cloud.google.com/backend-config: '{"default": "mc-backendconfig"}'
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    {{- include "mc.selectorLabels" . | nindent 4 }}